format: audio_format
playlists:
  - name: playlist_name
    id: playlist_id
overrides:
  - spotify: spotify_track_id
    youtube: youtube_video_id
interceptor_interval: 0
interceptor_ws_port: 8010
vdj_ws_port: 8000