format: audio_format
playlists:
  - name: playlist_name
    id: playlist_id
overrides:
  - spotify: spotify_track_id
    youtube: youtube_video_id
interceptor_interval: 0
interceptor_position_buffer: 100
vdj_ws_port: 8000
display_lines_before: 1
display_lines_after: 1